module.exports = [
    {
        "id": "0",
        "name": "FREE",
        "price": 0.00,
        "tax": 0.00,
        "total": 0.00,
        "surveyCount": 5,
        "billingCycle": 1,
        "textSuport": false,
        "textResponses": 0,
        "surveyLogo": false,
    },
    {
        "id": "1",
        "name": "BASIC",
        "price": 30.00,
        "tax": 1.87,
        "total": 31.87,
        "surveyCount": 100,
        "billingCycle": 1,
        "textSuport": false,
        "textResponses": 0,
        "surveyLogo": false
    },
    {
        "id": "2",
        "name": "PRO",
        "price": 35.00,
        "tax": 2.19,
        "total": 37.19,
        "surveyCount": 99999,
        "billingCycle": 1,
        "textSuport": true,
        "textResponses": 999999999999999,
        "surveyLogo": false
    },
    {
        "id": "3",
        "name": "ELITE",
        "price": 99.00,
        "tax": 6.19,
        "total": 105.19,
        "surveyCount": 99999,
        "billingCycle": 1,
        "textSuport": true,
        "textResponses": 999999999999999,
        "surveyLogo": true
    },
    {
        "id": "4",
        "name": "BASIC ANNUALLY",
        "price": 360.00,
        "tax": 22.50,
        "total": 382.50,
        "surveyCount": 1200,
        "billingCycle": 12,
        "textSuport": false,
        "textResponses": 100,
        "surveyLogo": false
    },
    {
        "id": "5",
        "name": "PRO ANNUALLY",
        "price": 420.00,
        "tax": 26.25,
        "total": 446.25,
        "surveyCount": 99999,
        "billingCycle": 12,
        "textSuport": true,
        "textResponses": 999999999999999,
        "surveyLogo": false
    },
    {
        "id": "6",
        "name": "ELITE ANNUALLY",
        "price": 1188.00,
        "tax": 74.25,
        "total": 1262.25,
        "surveyCount": 99999,
        "billingCycle": 12,
        "textSuport": true,
        "textResponses": 999999999999999,
        "surveyLogo": true
    }
]